### PR TITLE
Add smartpost support

### PR DESCRIPTION
**Pull request by mtthwgry**
@zreisman Can you take a look at this?

### CODE REVIEW

**Comment by mtthwgry** [comment]
@zreisman can you please review this?

**Comment by zreisman** [comment]
Looks good.

**Comment by mtthwgry** [comment]
@zreisman can you label it as peer reviewed please 😀

**Comment by zreisman** [comment]
There wasnt the option

_Zach Reisman_
Ruby on Rails Engineer

TouchofModern.com https://www.touchofmodern.com/
Office:  350 Rhode Island St, Suite 400, San Francisco, CA 94103
Warehouse: 30063 Ahern Ave., Union City, CA 94587
Find us on: Facebook https://www.facebook.com/touchofmodern\* · *Twitter
https://twitter.com/touchofmodern

We're hiring!
http://t.sigopn03.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7fKbv2W1q0JJ42BWbcRW8q5y9d56dR_lf2QqdZg02?t=http%3A%2F%2Fcareers.touchofmodern.com%2F&si=5319641602719744&pi=d5905a11-8254-4121-94a9-e0b9812dc264

**Pull request merged**
